In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
import sys, importlib
from pathlib import Path
sys.path.insert(0, str(Path().resolve().parent))

from pathlib import Path
from src.data.data_processing import Polynomial, Polynomial_CODI, RNG
from src.data.data_processing import TOKEN_DICT as CODI_TOKEN_DICT 
import numpy as np
import torch 
from typing import Dict

In [ ]:
n_data_per_seq = 5000 
split_ratio = 0.5 

for total_seqs in [3, 4, 8, 10]:
    for mod in [50, 41]: 
        n_data_per_len = [n_data_per_seq for _ in range(total_seqs)]
        split_probs_per_len = [split_ratio for _ in range(total_seqs)] 

        Polynomial_Cot_Gen = Polynomial(mod=mod, save_dir=Path(f'../data/polynomial_data/seq_{total_seqs}/num_{n_data_per_seq}/mod_{mod}/cot'), cot=True)
        Polynomial_NonCot_Gen = Polynomial(mod=mod, save_dir=Path(f'../data/polynomial_data/seq_{total_seqs}/num_{n_data_per_seq}/mod_{mod}/not_cot'), cot=False)
        Polynomial_CODI_Gen = Polynomial_CODI(mod=mod, save_dir=Path(f'../data/polynomial_data/seq_{total_seqs}/num_{n_data_per_seq}/mod_{mod}/codi'), cot=True) 

        Polynomial_Cot_Gen.generate_datafiles(n_data_per_len, split_probs_per_len, rng = np.random.default_rng(0))
        Polynomial_NonCot_Gen.generate_datafiles(n_data_per_len, split_probs_per_len, rng = np.random.default_rng(0))
        Polynomial_CODI_Gen.generate_datafiles(n_data_per_len, split_probs_per_len, rng = np.random.default_rng(0))

### Some Sanity Check Script

In [6]:
poly_cot = Polynomial_Cot_Gen.load_data([i+1 for i in range(total_seqs)], 'train')
poly_codi = Polynomial_CODI_Gen.load_data([i+1 for i in range(total_seqs)], 'train') 

In [7]:
poly_cot[6000]

array([58, 25, 18, 33, 62, 25,  0,  1, 63, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63], dtype=int32)

In [8]:
poly_codi[6000]

array([58, 25, 18, 33, 62, 25,  0, 64,  1, 63, 63, 63, 63, 63, 63, 63, 63,
       63, 63, 63, 63, 63, 63, 63], dtype=int32)

In [9]:
poly_codi

array([[58, 35, 62, ..., 63, 63, 63],
       [58,  5, 62, ..., 63, 63, 63],
       [58,  7, 62, ..., 63, 63, 63],
       ...,
       [58, 26, 38, ..., 64, 16, 63],
       [58, 10, 10, ..., 64,  8, 63],
       [58, 30, 28, ..., 64, 13, 63]], dtype=int32)

In [10]:
CODI_TOKEN_DICT

{'polynomial': 58,
 'parity': 59,
 'binary_copy': 60,
 'BoS': 61,
 'EoI': 62,
 'EoS': 63,
 'ANS': 64,
 'BoT': 65,
 'EoT': 66,
 'PAD': 67}